# Environment snapshot and restore helpers

_llmproxy_snapshot_env() {
  if [[ -n "${_LLMPROXY_SAVED:-}" ]]; then
    return 0
  fi
  export _LLMPROXY_SAVED=1
  export _LLMPROXY_ORIG_ANTHROPIC_BASE_URL="${ANTHROPIC_BASE_URL-}"
  export _LLMPROXY_ORIG_ANTHROPIC_AUTH_TOKEN="${ANTHROPIC_AUTH_TOKEN-}"
  export _LLMPROXY_ORIG_ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY-}"
  export _LLMPROXY_ORIG_ANTHROPIC_MODEL="${ANTHROPIC_MODEL-}"
  export _LLMPROXY_ORIG_ANTHROPIC_DEFAULT_OPUS_MODEL="${ANTHROPIC_DEFAULT_OPUS_MODEL-}"
  export _LLMPROXY_ORIG_ANTHROPIC_DEFAULT_SONNET_MODEL="${ANTHROPIC_DEFAULT_SONNET_MODEL-}"
  export _LLMPROXY_ORIG_ANTHROPIC_DEFAULT_HAIKU_MODEL="${ANTHROPIC_DEFAULT_HAIKU_MODEL-}"
  export _LLMPROXY_ORIG_CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="${CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC-}"
}

_llmproxy_restore_env() {
  if [[ -z "${_LLMPROXY_SAVED:-}" ]]; then
    unset ANTHROPIC_BASE_URL ANTHROPIC_AUTH_TOKEN ANTHROPIC_MODEL
    unset ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
    return 0
  fi
  export ANTHROPIC_BASE_URL="${_LLMPROXY_ORIG_ANTHROPIC_BASE_URL-}"
  export ANTHROPIC_AUTH_TOKEN="${_LLMPROXY_ORIG_ANTHROPIC_AUTH_TOKEN-}"
  export ANTHROPIC_API_KEY="${_LLMPROXY_ORIG_ANTHROPIC_API_KEY-}"
  export ANTHROPIC_MODEL="${_LLMPROXY_ORIG_ANTHROPIC_MODEL-}"
  export ANTHROPIC_DEFAULT_OPUS_MODEL="${_LLMPROXY_ORIG_ANTHROPIC_DEFAULT_OPUS_MODEL-}"
  export ANTHROPIC_DEFAULT_SONNET_MODEL="${_LLMPROXY_ORIG_ANTHROPIC_DEFAULT_SONNET_MODEL-}"
  export ANTHROPIC_DEFAULT_HAIKU_MODEL="${_LLMPROXY_ORIG_ANTHROPIC_DEFAULT_HAIKU_MODEL-}"
  export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="${_LLMPROXY_ORIG_CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC-}"
}

_llmproxy_clear_proxy_env() {
  if [[ "${ANTHROPIC_BASE_URL-}" == "${CLIPROXY_URL-}" ]]; then
    unset ANTHROPIC_BASE_URL
  fi
  if [[ "${ANTHROPIC_AUTH_TOKEN-}" == "${CLIPROXY_KEY-}" ]]; then
    unset ANTHROPIC_AUTH_TOKEN
  fi
  if [[ -z "${ANTHROPIC_BASE_URL-}" && -z "${ANTHROPIC_AUTH_TOKEN-}" ]]; then
    unset ANTHROPIC_MODEL ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
  fi
}
